server:
  port: 8443
  ssl:
    key-store-password: password
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-alias: tomcat
        
disableEmailVerification: true
spring:
  #populate your smtp host, port, username and password
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
         
logging:
  level:
    root: INFO
    com.memorynotfound: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG